version: '3.9'
services:
    nango-db:
        image: postgres
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '${NANGO_DB_PORT:-5432}:5432'
        volumes:
            - ./nango-data:/var/lib/postgresql/data
        networks:
            - nango

    nango-server:
        image: nangohq/nango-server
        container_name: nango-server
        volumes:
            - ./packages/server/providers.yaml:/usr/nango-server/src/packages/server/providers.yaml
            - ./packages/server/NangoActivity.json:/usr/nango-server/src/packages/server/NangoActivity.json
        restart: always
        ports:
            - '3003:3003'
        depends_on:
            - nango-db
        networks:
            - nango

networks:
    nango:
